-- Seed the discovery source list with ATS boards verified live when this
-- migration was written (Aug 2026): every slug below answered its provider's
-- public API with a non-empty job board.
--
-- A starting set, not a fixed one. The weekly board-discovery cron adds
-- companies from YC's directory, and rows can be added or disabled from
-- Settings -> Sources without a deploy.

insert into job_sources (kind, name, config, enabled, priority) values
  ('ashby', '1Password', '{"org": "1password", "displayName": "1Password"}'::jsonb, true, 1),
  ('greenhouse', 'Affirm', '{"board": "affirm", "company": "Affirm"}'::jsonb, true, 1),
  ('ashby', 'Airbyte', '{"org": "airbyte", "displayName": "Airbyte"}'::jsonb, true, 1),
  ('greenhouse', 'Airtable', '{"board": "airtable", "company": "Airtable"}'::jsonb, true, 1),
  ('greenhouse', 'Akuna Capital', '{"board": "akunacapital", "company": "Akuna Capital"}'::jsonb, true, 1),
  ('greenhouse', 'Alloy', '{"board": "alloy", "company": "Alloy"}'::jsonb, true, 1),
  ('greenhouse', 'Amplitude', '{"board": "amplitude", "company": "Amplitude"}'::jsonb, true, 1),
  ('greenhouse', 'Anthropic', '{"board": "anthropic", "company": "Anthropic"}'::jsonb, true, 1),
  ('greenhouse', 'Asana', '{"board": "asana", "company": "Asana"}'::jsonb, true, 1),
  ('greenhouse', 'Astranis', '{"board": "astranis", "company": "Astranis"}'::jsonb, true, 1),
  ('ashby', 'Astronomer', '{"org": "astronomer", "displayName": "Astronomer"}'::jsonb, true, 1),
  ('ashby', 'Baseten', '{"org": "baseten", "displayName": "Baseten"}'::jsonb, true, 1),
  ('lever', 'Belvedere Trading', '{"company": "belvederetrading", "displayName": "Belvedere Trading"}'::jsonb, true, 1),
  ('greenhouse', 'Brex', '{"board": "brex", "company": "Brex"}'::jsonb, true, 1),
  ('greenhouse', 'Buildkite', '{"board": "buildkite", "company": "Buildkite"}'::jsonb, true, 1),
  ('greenhouse', 'Carta', '{"board": "carta", "company": "Carta"}'::jsonb, true, 1),
  ('ashby', 'Cerebras', '{"org": "cerebras", "displayName": "Cerebras"}'::jsonb, true, 1),
  ('greenhouse', 'Checkr', '{"board": "checkr", "company": "Checkr"}'::jsonb, true, 1),
  ('greenhouse', 'Chime', '{"board": "chime", "company": "Chime"}'::jsonb, true, 1),
  ('greenhouse', 'CircleCI', '{"board": "circleci", "company": "CircleCI"}'::jsonb, true, 1),
  ('greenhouse', 'ClickHouse', '{"board": "clickhouse", "company": "ClickHouse"}'::jsonb, true, 1),
  ('greenhouse', 'Cloudflare', '{"board": "cloudflare", "company": "Cloudflare"}'::jsonb, true, 1),
  ('greenhouse', 'Cockroach Labs', '{"board": "cockroachlabs", "company": "Cockroach Labs"}'::jsonb, true, 1),
  ('ashby', 'Cohere', '{"org": "cohere", "displayName": "Cohere"}'::jsonb, true, 1),
  ('greenhouse', 'Coinbase', '{"board": "coinbase", "company": "Coinbase"}'::jsonb, true, 1),
  ('ashby', 'Confluent', '{"org": "confluent", "displayName": "Confluent"}'::jsonb, true, 1),
  ('greenhouse', 'CoreWeave', '{"board": "coreweave", "company": "CoreWeave"}'::jsonb, true, 1),
  ('greenhouse', 'Databricks', '{"board": "databricks", "company": "Databricks"}'::jsonb, true, 1),
  ('greenhouse', 'Datadog', '{"board": "datadog", "company": "Datadog"}'::jsonb, true, 1),
  ('greenhouse', 'Discord', '{"board": "discord", "company": "Discord"}'::jsonb, true, 1),
  ('greenhouse', 'Dropbox', '{"board": "dropbox", "company": "Dropbox"}'::jsonb, true, 1),
  ('greenhouse', 'Duolingo', '{"board": "duolingo", "company": "Duolingo"}'::jsonb, true, 1),
  ('greenhouse', 'Elastic', '{"board": "elastic", "company": "Elastic"}'::jsonb, true, 1),
  ('greenhouse', 'Figma', '{"board": "figma", "company": "Figma"}'::jsonb, true, 1),
  ('ashby', 'Fireworks AI', '{"org": "fireworks", "displayName": "Fireworks AI"}'::jsonb, true, 1),
  ('greenhouse', 'Fivetran', '{"board": "fivetran", "company": "Fivetran"}'::jsonb, true, 1),
  ('greenhouse', 'Flow Traders', '{"board": "flowtraders", "company": "Flow Traders"}'::jsonb, true, 1),
  ('greenhouse', 'GitLab', '{"board": "gitlab", "company": "GitLab"}'::jsonb, true, 1),
  ('greenhouse', 'Gusto', '{"board": "gusto", "company": "Gusto"}'::jsonb, true, 1),
  ('greenhouse', 'Hightouch', '{"board": "hightouch", "company": "Hightouch"}'::jsonb, true, 1),
  ('greenhouse', 'IMC Trading', '{"board": "imc", "company": "IMC Trading"}'::jsonb, true, 1),
  ('greenhouse', 'Instacart', '{"board": "instacart", "company": "Instacart"}'::jsonb, true, 1),
  ('greenhouse', 'Jane Street', '{"board": "janestreet", "company": "Jane Street"}'::jsonb, true, 1),
  ('greenhouse', 'Jump Trading', '{"board": "jumptrading", "company": "Jump Trading"}'::jsonb, true, 1),
  ('greenhouse', 'LaunchDarkly', '{"board": "launchdarkly", "company": "LaunchDarkly"}'::jsonb, true, 1),
  ('ashby', 'Linear', '{"org": "linear", "displayName": "Linear"}'::jsonb, true, 1),
  ('greenhouse', 'Lyft', '{"board": "lyft", "company": "Lyft"}'::jsonb, true, 1),
  ('greenhouse', 'Marqeta', '{"board": "marqeta", "company": "Marqeta"}'::jsonb, true, 1),
  ('greenhouse', 'Mercury', '{"board": "mercury", "company": "Mercury"}'::jsonb, true, 1),
  ('ashby', 'Middesk', '{"org": "middesk", "displayName": "Middesk"}'::jsonb, true, 1),
  ('greenhouse', 'Mixpanel', '{"board": "mixpanel", "company": "Mixpanel"}'::jsonb, true, 1),
  ('ashby', 'Modal', '{"org": "modal", "displayName": "Modal"}'::jsonb, true, 1),
  ('greenhouse', 'MongoDB', '{"board": "mongodb", "company": "MongoDB"}'::jsonb, true, 1),
  ('greenhouse', 'Neo4j', '{"board": "neo4j", "company": "Neo4j"}'::jsonb, true, 1),
  ('greenhouse', 'Netlify', '{"board": "netlify", "company": "Netlify"}'::jsonb, true, 1),
  ('ashby', 'Notion', '{"org": "notion", "displayName": "Notion"}'::jsonb, true, 1),
  ('greenhouse', 'Nuro', '{"board": "nuro", "company": "Nuro"}'::jsonb, true, 1),
  ('greenhouse', 'Okta', '{"board": "okta", "company": "Okta"}'::jsonb, true, 1),
  ('greenhouse', 'Old Mission Capital', '{"board": "oldmissioncapital", "company": "Old Mission Capital"}'::jsonb, true, 1),
  ('ashby', 'OpenAI', '{"org": "openai", "displayName": "OpenAI"}'::jsonb, true, 1),
  ('ashby', 'Persona', '{"org": "persona", "displayName": "Persona"}'::jsonb, true, 1),
  ('greenhouse', 'Pinterest', '{"board": "pinterest", "company": "Pinterest"}'::jsonb, true, 1),
  ('ashby', 'Plaid', '{"org": "plaid", "displayName": "Plaid"}'::jsonb, true, 1),
  ('greenhouse', 'PlanetScale', '{"board": "planetscale", "company": "PlanetScale"}'::jsonb, true, 1),
  ('ashby', 'Prefect', '{"org": "prefect", "displayName": "Prefect"}'::jsonb, true, 1),
  ('ashby', 'Ramp', '{"org": "ramp", "displayName": "Ramp"}'::jsonb, true, 1),
  ('greenhouse', 'Reddit', '{"board": "reddit", "company": "Reddit"}'::jsonb, true, 1),
  ('ashby', 'Redis', '{"org": "redis", "displayName": "Redis"}'::jsonb, true, 1),
  ('greenhouse', 'Relativity Space', '{"board": "relativity", "company": "Relativity Space"}'::jsonb, true, 1),
  ('ashby', 'Render', '{"org": "render", "displayName": "Render"}'::jsonb, true, 1),
  ('greenhouse', 'Robinhood', '{"board": "robinhood", "company": "Robinhood"}'::jsonb, true, 1),
  ('greenhouse', 'Roblox', '{"board": "roblox", "company": "Roblox"}'::jsonb, true, 1),
  ('greenhouse', 'Rocket Lab', '{"board": "rocketlab", "company": "Rocket Lab"}'::jsonb, true, 1),
  ('greenhouse', 'Samsara', '{"board": "samsara", "company": "Samsara"}'::jsonb, true, 1),
  ('ashby', 'Saronic', '{"org": "saronic", "displayName": "Saronic"}'::jsonb, true, 1),
  ('greenhouse', 'Scale AI', '{"board": "scaleai", "company": "Scale AI"}'::jsonb, true, 1),
  ('ashby', 'Sentry', '{"org": "sentry", "displayName": "Sentry"}'::jsonb, true, 1),
  ('ashby', 'Shield AI', '{"org": "shield-ai", "displayName": "Shield AI"}'::jsonb, true, 1),
  ('ashby', 'Skydio', '{"org": "skydio", "displayName": "Skydio"}'::jsonb, true, 1),
  ('ashby', 'Snowflake', '{"org": "snowflake", "displayName": "Snowflake"}'::jsonb, true, 1),
  ('greenhouse', 'Spire Global', '{"board": "spire", "company": "Spire Global"}'::jsonb, true, 1),
  ('greenhouse', 'Squarepoint Capital', '{"board": "squarepointcapital", "company": "Squarepoint Capital"}'::jsonb, true, 1),
  ('greenhouse', 'Stripe', '{"board": "stripe", "company": "Stripe"}'::jsonb, true, 1),
  ('ashby', 'Supabase', '{"org": "supabase", "displayName": "Supabase"}'::jsonb, true, 1),
  ('greenhouse', 'Tailscale', '{"board": "tailscale", "company": "Tailscale"}'::jsonb, true, 1),
  ('ashby', 'Temporal', '{"org": "temporal", "displayName": "Temporal"}'::jsonb, true, 1),
  ('ashby', 'Unit', '{"org": "unit", "displayName": "Unit"}'::jsonb, true, 1),
  ('ashby', 'Vanta', '{"org": "vanta", "displayName": "Vanta"}'::jsonb, true, 1),
  ('greenhouse', 'Vercel', '{"board": "vercel", "company": "Vercel"}'::jsonb, true, 1),
  ('greenhouse', 'Verkada', '{"board": "verkada", "company": "Verkada"}'::jsonb, true, 1),
  ('greenhouse', 'Waymo', '{"board": "waymo", "company": "Waymo"}'::jsonb, true, 1),
  ('ashby', 'Zapier', '{"org": "zapier", "displayName": "Zapier"}'::jsonb, true, 1),
  ('lever', 'Zoox', '{"company": "zoox", "displayName": "Zoox"}'::jsonb, true, 1)
on conflict (kind, name) do nothing;

-- The curated Summer 2027 internship list maintained by Pitt CSC and Simplify.
-- One request covers several hundred companies, so it runs ahead of any
-- individual board.
insert into job_sources (kind, name, config, enabled, priority) values
  ('simplify', 'Pitt CSC x Simplify (Summer 2027)',
   '{"repo": "SimplifyJobs/Summer2027-Internships", "branch": "dev", "term": "Summer 2027"}'::jsonb,
   true, 10)
on conflict (kind, name) do nothing;

-- Pre-classify these companies so category filters and the company-preference
-- component work before any of their jobs have been seen. A category set by
-- hand later is never overwritten.
insert into companies (name, slug, category) values
  ('1Password', '1password', 'devtools'),
  ('Affirm', 'affirm', 'fintech'),
  ('Airbyte', 'airbyte', 'infrastructure'),
  ('Airtable', 'airtable', 'bigtech'),
  ('Akuna Capital', 'akuna-capital', 'trading'),
  ('Alloy', 'alloy', 'fintech'),
  ('Amplitude', 'amplitude', 'bigtech'),
  ('Anthropic', 'anthropic', 'ai'),
  ('Asana', 'asana', 'bigtech'),
  ('Astranis', 'astranis', 'defense'),
  ('Astronomer', 'astronomer', 'infrastructure'),
  ('Baseten', 'baseten', 'ai'),
  ('Belvedere Trading', 'belvedere-trading', 'trading'),
  ('Brex', 'brex', 'fintech'),
  ('Buildkite', 'buildkite', 'devtools'),
  ('Carta', 'carta', 'fintech'),
  ('Cerebras', 'cerebras', 'ai'),
  ('Checkr', 'checkr', 'fintech'),
  ('Chime', 'chime', 'fintech'),
  ('CircleCI', 'circleci', 'devtools'),
  ('ClickHouse', 'clickhouse', 'infrastructure'),
  ('Cloudflare', 'cloudflare', 'infrastructure'),
  ('Cockroach Labs', 'cockroach', 'infrastructure'),
  ('Cohere', 'cohere', 'ai'),
  ('Coinbase', 'coinbase', 'fintech'),
  ('Confluent', 'confluent', 'infrastructure'),
  ('CoreWeave', 'coreweave', 'ai'),
  ('Databricks', 'databricks', 'infrastructure'),
  ('Datadog', 'datadog', 'infrastructure'),
  ('Discord', 'discord', 'bigtech'),
  ('Dropbox', 'dropbox', 'bigtech'),
  ('Duolingo', 'duolingo', 'bigtech'),
  ('Elastic', 'elastic', 'infrastructure'),
  ('Figma', 'figma', 'bigtech'),
  ('Fireworks AI', 'fireworks-ai', 'ai'),
  ('Fivetran', 'fivetran', 'infrastructure'),
  ('Flow Traders', 'flow-traders', 'trading'),
  ('GitLab', 'gitlab', 'devtools'),
  ('Gusto', 'gusto', 'fintech'),
  ('Hightouch', 'hightouch', 'infrastructure'),
  ('IMC Trading', 'imc-trading', 'trading'),
  ('Instacart', 'instacart', 'bigtech'),
  ('Jane Street', 'jane-street', 'trading'),
  ('Jump Trading', 'jump-trading', 'trading'),
  ('LaunchDarkly', 'launchdarkly', 'devtools'),
  ('Linear', 'linear', 'devtools'),
  ('Lyft', 'lyft', 'bigtech'),
  ('Marqeta', 'marqeta', 'fintech'),
  ('Mercury', 'mercury', 'fintech'),
  ('Middesk', 'middesk', 'fintech'),
  ('Mixpanel', 'mixpanel', 'bigtech'),
  ('Modal', 'modal', 'ai'),
  ('MongoDB', 'mongodb', 'infrastructure'),
  ('Neo4j', 'neo4j', 'infrastructure'),
  ('Netlify', 'netlify', 'devtools'),
  ('Notion', 'notion', 'bigtech'),
  ('Nuro', 'nuro', 'robotics'),
  ('Okta', 'okta', 'devtools'),
  ('Old Mission Capital', 'old-mission-capital', 'trading'),
  ('OpenAI', 'openai', 'ai'),
  ('Persona', 'persona', 'fintech'),
  ('Pinterest', 'pinterest', 'bigtech'),
  ('Plaid', 'plaid', 'fintech'),
  ('PlanetScale', 'planetscale', 'infrastructure'),
  ('Prefect', 'prefect', 'infrastructure'),
  ('Ramp', 'ramp', 'fintech'),
  ('Reddit', 'reddit', 'bigtech'),
  ('Redis', 'redis', 'infrastructure'),
  ('Relativity Space', 'relativity-space', 'defense'),
  ('Render', 'render', 'infrastructure'),
  ('Robinhood', 'robinhood', 'fintech'),
  ('Roblox', 'roblox', 'bigtech'),
  ('Rocket Lab', 'rocket-lab', 'defense'),
  ('Samsara', 'samsara', 'bigtech'),
  ('Saronic', 'saronic', 'robotics'),
  ('Scale AI', 'scale-ai', 'ai'),
  ('Sentry', 'sentry', 'devtools'),
  ('Shield AI', 'shield-ai', 'robotics'),
  ('Skydio', 'skydio', 'robotics'),
  ('Snowflake', 'snowflake', 'infrastructure'),
  ('Spire Global', 'spire-global', 'defense'),
  ('Squarepoint Capital', 'squarepoint-capital', 'trading'),
  ('Stripe', 'stripe', 'other'),
  ('Supabase', 'supabase', 'infrastructure'),
  ('Tailscale', 'tailscale', 'devtools'),
  ('Temporal', 'temporal', 'infrastructure'),
  ('Unit', 'unit', 'fintech'),
  ('Vanta', 'vanta', 'devtools'),
  ('Vercel', 'vercel', 'devtools'),
  ('Verkada', 'verkada', 'bigtech'),
  ('Waymo', 'waymo', 'robotics'),
  ('Zapier', 'zapier', 'devtools'),
  ('Zoox', 'zoox', 'robotics')
on conflict (slug) do update set
  category = case
    when companies.category = 'other' then excluded.category
    else companies.category
  end;
