-- Second wave of discovery sources, probed live (Aug 2026): every slug below
-- returned a non-empty board from its provider's public API.
--
-- Adds defense/autonomy (Anduril, Applied Intuition, Figure, Skydio, Zoox),
-- quant trading (HRT, XTX, Citadel Securities, PDT, Point72), AI labs and
-- silicon (Groq, Cerebras, Tenstorrent), data infrastructure (ClickHouse,
-- Temporal, Redpanda) and developer tools.

insert into job_sources (kind, name, config, enabled, priority) values
  ('greenhouse', 'Adyen', '{"board": "adyen", "company": "Adyen"}'::jsonb, true, 1),
  ('greenhouse', 'Alloy', '{"board": "alloy", "company": "Alloy"}'::jsonb, true, 1),
  ('lever', 'Anchorage', '{"company": "anchorage", "displayName": "Anchorage"}'::jsonb, true, 1),
  ('greenhouse', 'Andurilindustries', '{"board": "andurilindustries", "company": "Andurilindustries"}'::jsonb, true, 1),
  ('greenhouse', 'AQR', '{"board": "aqr", "company": "AQR"}'::jsonb, true, 1),
  ('ashby', 'Braintrust', '{"org": "braintrust", "displayName": "Braintrust"}'::jsonb, true, 1),
  ('ashby', 'Coder', '{"org": "coder", "displayName": "Coder"}'::jsonb, true, 1),
  ('ashby', 'Column', '{"org": "column", "displayName": "Column"}'::jsonb, true, 1),
  ('greenhouse', 'Comet', '{"board": "comet", "company": "Comet"}'::jsonb, true, 1),
  ('greenhouse', 'Coursera', '{"board": "coursera", "company": "Coursera"}'::jsonb, true, 1),
  ('greenhouse', 'Cribl', '{"board": "cribl", "company": "Cribl"}'::jsonb, true, 1),
  ('ashby', 'Cursor', '{"org": "cursor", "displayName": "Cursor"}'::jsonb, true, 1),
  ('ashby', 'Decagon', '{"org": "decagon", "displayName": "Decagon"}'::jsonb, true, 1),
  ('greenhouse', 'Descript', '{"board": "descript", "company": "Descript"}'::jsonb, true, 1),
  ('greenhouse', 'Discord', '{"board": "discord", "company": "Discord"}'::jsonb, true, 1),
  ('greenhouse', 'Dremio', '{"board": "dremio", "company": "Dremio"}'::jsonb, true, 1),
  ('ashby', 'Elevenlabs', '{"org": "elevenlabs", "displayName": "Elevenlabs"}'::jsonb, true, 1),
  ('greenhouse', 'Epic Games', '{"board": "epicgames", "company": "Epic Games"}'::jsonb, true, 1),
  ('greenhouse', 'Epirus', '{"board": "epirus", "company": "Epirus"}'::jsonb, true, 1),
  ('ashby', 'Etched', '{"org": "etched", "displayName": "Etched"}'::jsonb, true, 1),
  ('greenhouse', 'Figure', '{"board": "figure", "company": "Figure"}'::jsonb, true, 1),
  ('greenhouse', 'Figureai', '{"board": "figureai", "company": "Figureai"}'::jsonb, true, 1),
  ('greenhouse', 'Fireblocks', '{"board": "fireblocks", "company": "Fireblocks"}'::jsonb, true, 1),
  ('greenhouse', 'Forter', '{"board": "forter", "company": "Forter"}'::jsonb, true, 1),
  ('greenhouse', 'Galileo', '{"board": "galileo", "company": "Galileo"}'::jsonb, true, 1),
  ('ashby', 'Gecko Robotics', '{"org": "gecko-robotics", "displayName": "Gecko Robotics"}'::jsonb, true, 1),
  ('greenhouse', 'Gemini', '{"board": "gemini", "company": "Gemini"}'::jsonb, true, 1),
  ('lever', 'Gopuff', '{"company": "gopuff", "displayName": "Gopuff"}'::jsonb, true, 1),
  ('ashby', 'Harvey', '{"org": "harvey", "displayName": "Harvey"}'::jsonb, true, 1),
  ('lever', 'Hermeus', '{"company": "hermeus", "displayName": "Hermeus"}'::jsonb, true, 1),
  ('greenhouse', 'Honeycomb', '{"board": "honeycomb", "company": "Honeycomb"}'::jsonb, true, 1),
  ('ashby', 'Inngest', '{"org": "inngest", "displayName": "Inngest"}'::jsonb, true, 1),
  ('greenhouse', 'IonQ', '{"board": "ionq", "company": "IonQ"}'::jsonb, true, 1),
  ('ashby', 'Lancedb', '{"org": "lancedb", "displayName": "Lancedb"}'::jsonb, true, 1),
  ('ashby', 'Langchain', '{"org": "langchain", "displayName": "Langchain"}'::jsonb, true, 1),
  ('greenhouse', 'Lightmatter', '{"board": "lightmatter", "company": "Lightmatter"}'::jsonb, true, 1),
  ('greenhouse', 'Lithic', '{"board": "lithic", "company": "Lithic"}'::jsonb, true, 1),
  ('ashby', 'Llamaindex', '{"org": "llamaindex", "displayName": "Llamaindex"}'::jsonb, true, 1),
  ('lever', 'Logrocket', '{"company": "logrocket", "displayName": "Logrocket"}'::jsonb, true, 1),
  ('greenhouse', 'Lucidmotors', '{"board": "lucidmotors", "company": "Lucidmotors"}'::jsonb, true, 1),
  ('ashby', 'Marqeta', '{"org": "marqeta-inc", "displayName": "Marqeta"}'::jsonb, true, 1),
  ('ashby', 'Materialize', '{"org": "materialize", "displayName": "Materialize"}'::jsonb, true, 1),
  ('ashby', 'MotherDuck', '{"org": "motherduck", "displayName": "MotherDuck"}'::jsonb, true, 1),
  ('greenhouse', 'Motional', '{"board": "motional", "company": "Motional"}'::jsonb, true, 1),
  ('greenhouse', 'Motive', '{"board": "motive", "company": "Motive"}'::jsonb, true, 1),
  ('ashby', 'n8n', '{"org": "n8n", "displayName": "n8n"}'::jsonb, true, 1),
  ('ashby', 'Neptune', '{"org": "neptune", "displayName": "Neptune"}'::jsonb, true, 1),
  ('greenhouse', 'Newrelic', '{"board": "newrelic", "company": "Newrelic"}'::jsonb, true, 1),
  ('ashby', 'Perplexity', '{"org": "perplexity", "displayName": "Perplexity"}'::jsonb, true, 1),
  ('ashby', 'Pika', '{"org": "pika", "displayName": "Pika"}'::jsonb, true, 1),
  ('ashby', 'Pinecone', '{"org": "pinecone", "displayName": "Pinecone"}'::jsonb, true, 1),
  ('greenhouse', 'PingCAP', '{"board": "pingcap", "company": "PingCAP"}'::jsonb, true, 1),
  ('greenhouse', 'Point72', '{"board": "point72", "company": "Point72"}'::jsonb, true, 1),
  ('lever', 'Porter', '{"company": "porter", "displayName": "Porter"}'::jsonb, true, 1),
  ('ashby', 'PostHog', '{"org": "posthog", "displayName": "PostHog"}'::jsonb, true, 1),
  ('ashby', 'Primer', '{"org": "primer", "displayName": "Primer"}'::jsonb, true, 1),
  ('ashby', 'Quicknode', '{"org": "quicknode", "displayName": "Quicknode"}'::jsonb, true, 1),
  ('ashby', 'Ramp', '{"org": "ramp", "displayName": "Ramp"}'::jsonb, true, 1),
  ('ashby', 'Reka', '{"org": "reka", "displayName": "Reka"}'::jsonb, true, 1),
  ('ashby', 'Replit', '{"org": "replit", "displayName": "Replit"}'::jsonb, true, 1),
  ('lever', 'Rhombus Systems', '{"company": "rhombus-systems", "displayName": "Rhombus Systems"}'::jsonb, true, 1),
  ('lever', 'Rigetti', '{"company": "rigetti", "displayName": "Rigetti"}'::jsonb, true, 1),
  ('greenhouse', 'Riskified', '{"board": "riskified", "company": "Riskified"}'::jsonb, true, 1),
  ('greenhouse', 'Roblox', '{"board": "roblox", "company": "Roblox"}'::jsonb, true, 1),
  ('ashby', 'Runway Ml', '{"org": "runway-ml", "displayName": "Runway Ml"}'::jsonb, true, 1),
  ('ashby', 'Sardine', '{"org": "sardine", "displayName": "Sardine"}'::jsonb, true, 1),
  ('greenhouse', 'Schonfeld', '{"board": "schonfeld", "company": "Schonfeld"}'::jsonb, true, 1),
  ('greenhouse', 'Shield', '{"board": "shield", "company": "Shield"}'::jsonb, true, 1),
  ('ashby', 'Sierra', '{"org": "sierra", "displayName": "Sierra"}'::jsonb, true, 1),
  ('ashby', 'Sift', '{"org": "sift", "displayName": "Sift"}'::jsonb, true, 1),
  ('greenhouse', 'Singlestore', '{"board": "singlestore", "company": "Singlestore"}'::jsonb, true, 1),
  ('ashby', 'Socure', '{"org": "socure", "displayName": "Socure"}'::jsonb, true, 1),
  ('greenhouse', 'Stackblitz', '{"board": "stackblitz", "company": "Stackblitz"}'::jsonb, true, 1),
  ('greenhouse', 'Starburst', '{"board": "starburst", "company": "Starburst"}'::jsonb, true, 1),
  ('ashby', 'Suno', '{"org": "suno", "displayName": "Suno"}'::jsonb, true, 1),
  ('ashby', 'Synthesia', '{"org": "synthesia", "displayName": "Synthesia"}'::jsonb, true, 1),
  ('greenhouse', 'Tenstorrent', '{"board": "tenstorrent", "company": "Tenstorrent"}'::jsonb, true, 1),
  ('ashby', 'Trm', '{"org": "trm-labs", "displayName": "Trm"}'::jsonb, true, 1),
  ('ashby', 'Turbopuffer', '{"org": "turbopuffer", "displayName": "Turbopuffer"}'::jsonb, true, 1),
  ('greenhouse', 'Typeface', '{"board": "typeface", "company": "Typeface"}'::jsonb, true, 1),
  ('greenhouse', 'Udemy', '{"board": "udemy", "company": "Udemy"}'::jsonb, true, 1),
  ('greenhouse', 'Ursamajor', '{"board": "ursamajor", "company": "Ursamajor"}'::jsonb, true, 1),
  ('greenhouse', 'Vast', '{"board": "vast", "company": "Vast"}'::jsonb, true, 1),
  ('greenhouse', 'Warp', '{"board": "warp", "company": "Warp"}'::jsonb, true, 1),
  ('ashby', 'Weaviate', '{"org": "weaviate", "displayName": "Weaviate"}'::jsonb, true, 1),
  ('ashby', 'Windmill', '{"org": "windmill", "displayName": "Windmill"}'::jsonb, true, 1),
  ('ashby', 'Writer', '{"org": "writer", "displayName": "Writer"}'::jsonb, true, 1),
  ('greenhouse', 'xAI', '{"board": "xai", "company": "xAI"}'::jsonb, true, 1),
  ('greenhouse', 'Yugabyte', '{"board": "yugabyte", "company": "Yugabyte"}'::jsonb, true, 1),
  ('ashby', 'Zed', '{"org": "zed", "displayName": "Zed"}'::jsonb, true, 1),
  ('lever', 'Zilliz', '{"company": "zilliz", "displayName": "Zilliz"}'::jsonb, true, 1)
on conflict (kind, name) do nothing;

insert into companies (name, slug, category) values
  ('Adyen', 'adyen', 'fintech'),
  ('Alloy', 'alloy', 'fintech'),
  ('Anchorage', 'anchorage', 'fintech'),
  ('Andurilindustries', 'andurilindustries', 'robotics'),
  ('AQR', 'aqr', 'trading'),
  ('Braintrust', 'braintrust', 'ai'),
  ('Coder', 'coder', 'devtools'),
  ('Column', 'column', 'fintech'),
  ('Comet', 'comet', 'ai'),
  ('Coursera', 'coursera', 'bigtech'),
  ('Cribl', 'cribl', 'devtools'),
  ('Cursor', 'cursor', 'devtools'),
  ('Decagon', 'decagon', 'ai'),
  ('Descript', 'descript', 'bigtech'),
  ('Discord', 'discord', 'bigtech'),
  ('Dremio', 'dremio', 'infrastructure'),
  ('Elevenlabs', 'elevenlabs', 'ai'),
  ('Epic Games', 'epic-games', 'bigtech'),
  ('Epirus', 'epirus', 'defense'),
  ('Etched', 'etched', 'ai'),
  ('Figure', 'figure', 'robotics'),
  ('Figureai', 'figureai', 'robotics'),
  ('Fireblocks', 'fireblocks', 'fintech'),
  ('Forter', 'forter', 'fintech'),
  ('Galileo', 'galileo', 'ai'),
  ('Gecko Robotics', 'gecko-robotics', 'robotics'),
  ('Gemini', 'gemini', 'fintech'),
  ('Gopuff', 'gopuff', 'bigtech'),
  ('Harvey', 'harvey', 'ai'),
  ('Hermeus', 'hermeus', 'defense'),
  ('Honeycomb', 'honeycomb', 'devtools'),
  ('Inngest', 'inngest', 'infrastructure'),
  ('IonQ', 'ionq', 'bigtech'),
  ('Lancedb', 'lancedb', 'infrastructure'),
  ('Langchain', 'langchain', 'ai'),
  ('Lightmatter', 'lightmatter', 'bigtech'),
  ('Lithic', 'lithic', 'fintech'),
  ('Llamaindex', 'llamaindex', 'ai'),
  ('Logrocket', 'logrocket', 'devtools'),
  ('Lucidmotors', 'lucidmotors', 'robotics'),
  ('Marqeta', 'marqeta', 'fintech'),
  ('Materialize', 'materialize', 'infrastructure'),
  ('MotherDuck', 'motherduck', 'infrastructure'),
  ('Motional', 'motional', 'robotics'),
  ('Motive', 'motive', 'robotics'),
  ('n8n', 'n8n', 'devtools'),
  ('Neptune', 'neptune', 'ai'),
  ('Newrelic', 'newrelic', 'devtools'),
  ('Perplexity', 'perplexity', 'ai'),
  ('Pika', 'pika', 'ai'),
  ('Pinecone', 'pinecone', 'infrastructure'),
  ('PingCAP', 'pingcap', 'infrastructure'),
  ('Point72', 'point72', 'trading'),
  ('Porter', 'porter', 'infrastructure'),
  ('PostHog', 'posthog', 'devtools'),
  ('Primer', 'primer', 'defense'),
  ('Quicknode', 'quicknode', 'fintech'),
  ('Ramp', 'ramp', 'fintech'),
  ('Reka', 'reka', 'ai'),
  ('Replit', 'replit', 'devtools'),
  ('Rhombus Systems', 'rhombus-systems', 'bigtech'),
  ('Rigetti', 'rigetti', 'bigtech'),
  ('Riskified', 'riskified', 'fintech'),
  ('Roblox', 'roblox', 'bigtech'),
  ('Runway Ml', 'runway-ml', 'ai'),
  ('Sardine', 'sardine', 'fintech'),
  ('Schonfeld', 'schonfeld', 'trading'),
  ('Shield', 'shield', 'robotics'),
  ('Sierra', 'sierra', 'ai'),
  ('Sift', 'sift', 'fintech'),
  ('Singlestore', 'singlestore', 'infrastructure'),
  ('Socure', 'socure', 'fintech'),
  ('Stackblitz', 'stackblitz', 'devtools'),
  ('Starburst', 'starburst', 'infrastructure'),
  ('Suno', 'suno', 'ai'),
  ('Synthesia', 'synthesia', 'ai'),
  ('Tenstorrent', 'tenstorrent', 'ai'),
  ('Trm', 'trm', 'fintech'),
  ('Turbopuffer', 'turbopuffer', 'infrastructure'),
  ('Typeface', 'typeface', 'ai'),
  ('Udemy', 'udemy', 'bigtech'),
  ('Ursamajor', 'ursamajor', 'defense'),
  ('Vast', 'vast', 'defense'),
  ('Warp', 'warp', 'devtools'),
  ('Weaviate', 'weaviate', 'infrastructure'),
  ('Windmill', 'windmill', 'infrastructure'),
  ('Writer', 'writer', 'ai'),
  ('xAI', 'xai', 'ai'),
  ('Yugabyte', 'yugabyte', 'infrastructure'),
  ('Zed', 'zed', 'devtools'),
  ('Zilliz', 'zilliz', 'infrastructure')
on conflict (slug) do update set
  category = case
    when companies.category = 'other' then excluded.category
    else companies.category
  end;
